name: reviewdog
on: [pull_request]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          version: 2.17.0
          # github-pr-check, github-pr-review, github-check
          reporter: github-pr-check
          fail_on_error: true
          # added, diff_context, file, nofilter
          filter_mode: nofilter
